package com.teammanduk.adego.feature.create

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.teammanduk.adego.core.domain.usecase.ClearSelectedPlaceUseCase
import com.teammanduk.adego.core.domain.usecase.CreateRoomUseCase
import com.teammanduk.adego.core.domain.usecase.GetSelectedPlaceUseCase
import com.teammanduk.adego.core.model.Place
import com.teammanduk.adego.feature.create.model.CreateIntent
import com.teammanduk.adego.feature.create.model.CreateSideEffect
import com.teammanduk.adego.feature.create.model.CreateStep
import com.teammanduk.adego.feature.create.model.CreateUiState
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.channels.Channel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.receiveAsFlow
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import javax.inject.Inject

@HiltViewModel
class CreateViewModel @Inject constructor(
    private val getSelectedPlaceUseCase: GetSelectedPlaceUseCase,
    private val clearSelectedPlaceUseCase: ClearSelectedPlaceUseCase,
    private val createRoomUseCase: CreateRoomUseCase
) : ViewModel() {

    private val selectedPlaceFromUseCase: StateFlow<Place?> = getSelectedPlaceUseCase()
        .stateIn(
            scope = viewModelScope,
            started = SharingStarted.WhileSubscribed(5000),
            initialValue = null
        )

    private val _uiState = MutableStateFlow(CreateUiState())
    val uiState: StateFlow<CreateUiState> = _uiState.asStateFlow()

    private val _sideEffect = Channel<CreateSideEffect>()
    val sideEffect = _sideEffect.receiveAsFlow()

    init {
        viewModelScope.launch {
            clearSelectedPlaceUseCase() // 먼저 초기화
            selectedPlaceFromUseCase.collect { place ->
                place?.let { onIntent(CreateIntent.SelectPlace(it)) }
            }
        }
    }

    fun onIntent(intent: CreateIntent) {
        when (intent) {
            is CreateIntent.CreateRoom -> {
                createRoom(intent.userId, intent.userName)
            }

            CreateIntent.NavigateToSelectPlace -> {
                viewModelScope.launch {
                    _sideEffect.send(CreateSideEffect.NavigateToSelectPlace)
                }
            }

            CreateIntent.NavigateBack -> {
                viewModelScope.launch {
                    _sideEffect.send(CreateSideEffect.NavigateBack)
                }
            }

            else -> {
                _uiState.update { currentState ->
                    reduce(intent, currentState)
                }
            }
        }
    }

    private fun reduce(intent: CreateIntent, state: CreateUiState): CreateUiState {
        return when (intent) {
            is CreateIntent.SelectPlace -> {
                val autoGeneratedName = generateRoomName(
                    placeName = intent.place.name,
                    hour = state.selectedHour,
                    minute = state.selectedMinute
                )
                state.copy(
                    selectedPlace = intent.place,
                    meetingPlaceName = intent.place.name,
                    roomName = autoGeneratedName,
                    currentStep = calculateNextStep(state.copy(selectedPlace = intent.place))
                )
            }

            is CreateIntent.UpdateMeetingPlaceName -> {
                val autoGeneratedName = generateRoomName(
                    placeName = intent.placeName,
                    hour = state.selectedHour,
                    minute = state.selectedMinute
                )
                state.copy(
                    meetingPlaceName = intent.placeName,
                    roomName = autoGeneratedName
                )
            }

            is CreateIntent.UpdateRoomName -> {
                state.copy(roomName = intent.roomName)
            }

            is CreateIntent.SelectDate -> {
                state.copy(
                    selectedDate = intent.dateMillis,
                    currentStep = calculateNextStep(state.copy(selectedDate = intent.dateMillis))
                )
            }

            is CreateIntent.SelectTime -> {
                val autoGeneratedName = generateRoomName(
                    placeName = state.meetingPlaceName,
                    hour = intent.hour,
                    minute = intent.minute
                )
                state.copy(
                    selectedHour = intent.hour,
                    selectedMinute = intent.minute,
                    roomName = autoGeneratedName,
                    currentStep = calculateNextStep(
                        state.copy(
                            selectedHour = intent.hour,
                            selectedMinute = intent.minute
                        )
                    )
                )
            }

            is CreateIntent.ClearError -> {
                state.copy(error = null)
            }

            is CreateIntent.CreateRoom -> state // 이미 onIntent에서 처리됨
            CreateIntent.NavigateToSelectPlace -> state // SideEffect로 처리
            CreateIntent.NavigateBack -> state // SideEffect로 처리
        }
    }

    private fun calculateNextStep(state: CreateUiState): CreateStep {
        return when {
            state.selectedPlace == null -> CreateStep.PLACE_SELECTION
            state.selectedDate == null || state.selectedHour == null || state.selectedMinute == null -> CreateStep.TIME_SELECTION
            state.roomName.trim().isEmpty() -> CreateStep.ROOM_NAME_INPUT
            else -> CreateStep.READY_TO_CREATE
        }
    }

    private fun generateRoomName(placeName: String, hour: Int?, minute: Int?): String {
        return if (hour != null && minute != null) {
            val timeString = String.format("%02d시 %02d분", hour, minute)
            "$placeName $timeString 모임"
        } else if (placeName.isNotEmpty()) {
            "$placeName 모임"
        } else {
            ""
        }
    }

    /**
     * 방 생성
     */
    private fun createRoom(userId: String, userName: String) {
        viewModelScope.launch {
            try {
                val currentState = _uiState.value
                val roomName = currentState.roomName
                val dateMillis = currentState.selectedDate ?: return@launch
                val hour = currentState.selectedHour ?: return@launch
                val minute = currentState.selectedMinute ?: return@launch

                _uiState.update { it.copy(isCreating = true, error = null) }

                val place = currentState.selectedPlace
                    ?: throw IllegalStateException("장소가 선택되지 않았습니다")

                val dateTime = formatDateTime(dateMillis, hour, minute)

                val result = createRoomUseCase(
                    roomName = roomName,
                    destination = place,
                    dateTime = dateTime,
                    userId = userId,
                    userName = userName
                )

                result.onSuccess { roomId ->
                    _sideEffect.send(CreateSideEffect.NavigateToMap(roomId, userId))
                }.onFailure { exception ->
                    _uiState.update {
                        it.copy(error = exception.message ?: "방 생성에 실패했습니다")
                    }
                }
            } catch (e: Exception) {
                _uiState.update {
                    it.copy(error = e.message ?: "알 수 없는 오류가 발생했습니다")
                }
            } finally {
                _uiState.update { it.copy(isCreating = false) }
            }
        }
    }

    private fun formatDateTime(dateMillis: Long, hour: Int, minute: Int): String {
        val dateFormat = SimpleDateFormat("yyyy-MM-dd", Locale.KOREA)
        val date = dateFormat.format(Date(dateMillis))
        val time = String.format("%02d:%02d:00", hour, minute)
        return "${date}T$time"
    }
}
